 name: Canadian Remote Tech Writer Job Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run scraper
        run: python scraper.py
  


